# change default.cfg to your own config
# start: docker-compose up -d
# stop: docker-compose down
# logs: docker-compose logs
# state: docker-compose ps

version: '2'
services:
  bot:
   image: busbyjon/poloniexlendingbot:arm
   restart: always
   ports:
    - "0.0.0.0:8000:8000"
   env_file: ../secrets-bot.env

# copy complete repository and change the host port (8000 in 0.0.0.0:8000) for additional bots
