FROM busbyjon/armv6-python:2

RUN [ "cross-build-start" ]

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

RUN [ "cross-build-end" ]

CMD ["python","lendingbot.py"]

